### ISSUE TITLE
Is there a way to center the window?

### ISSUE THREAD

**Issue by sentialx** [rust-native-ui/libui-rs#74]
Currently when creating a window on macOS it shows in the left bottom corner. Is there a way to center the window?

**Comment by dertuxmalwieder** [comment]
That's a libui restriction. See also https://github.com/andlabs/ui/issues/162

**Comment by sentialx** [comment]
Wow, I almost forgot about this issue

**Comment by dertuxmalwieder** [comment]
I wish I did as well...

**Comment by NoraCodes** [comment]
wontfix unfortunately, because of the issue linked there. If that ever gets updated we will definitely incorporate that into the API, though!

**Comment by LoganDark** [comment]
~~Hey, [doesn't libui have a `uiWindowCenter` function?](https://github.com/andlabs/libui/search?q=uiWindowCenter&unscoped_q=uiWindowCenter)~~

Nevermind, it seems like that was removed because Wayland didn't support it.

**Comment by LoganDark** [comment]
For macOS only:
```rust
use iui::UI;
use iui::controls::Window;
use ui_sys::{uiControl, uiControlHandle};
use objc::runtime::Object;
use objc::{msg_send, sel, sel_impl};

#[cfg(target_os = "macos")]
pub fn window_center(ui: &UI, window: &mut Window) {
	unsafe {
		let handle = uiControlHandle(window.ptr() as *mut uiControl) as *mut Object;
		let _: () = msg_send![handle, center];
	}
}

#[cfg(not(target_os = "macos"))]
pub fn window_center(ui: &UI, window: &mut Window) {
	// no-op / not implemented
}
```
Basically, grabs a handle to the native NSWindow object, and tells it to center itself anyway. Even if libui doesn't expose a function for it.

Cross-platform is great, and I'd totally support creating a more robust version of this function that works on more than one platform, but for those who just want their thing to work _on macOS_, this is good enough.

It does pull in the `ui_sys` and `objc` dependencies though, so do pay attention to that.

The function itself can be safe, because provided `ui_sys` doesn't break its guarantee that calling `uiControlHandle` with a `uiWindow` will return an `NSWindow`, sending a message to it to center itself should never cause any UB. All this stuff is just unsafe because it's on the programmer to uphold those guarantees, and I think I did that well enough.
