### ISSUE TITLE
libui system build feature flag

### ISSUE THREAD

**Issue by NoraCodes** [rust-native-ui/libui-rs#8]
ui-sys building should be behind a feature flag. Not all users have CMake and Git, and not all users need to have them. We should allow users to use a binary distribution of libui and still build `iui` packages.

**Comment by andlabs** [comment]
How to package binary distributions recently came up in the main issue tracker (since my binary archives are now being automated by CI), so as an outsider I have to ask: how would a cargo user expect binaries to come? Would they be included with the repo? Downloaded from the upstream releases page, and if so, would there be a benefit to excluding the examples from that download? Built remotely and downloaded from that remote source? Something else?

**Comment by NoraCodes** [comment]
> how would a cargo user expect binaries to come

This is something of an open question in the Rust community. Personally, I prefer that the build tool builds the library, since that allows me to pin it at a specific commit. However, given the Rust toolchain's norms, a static linking capability would be better in this case, which doesn't make much sense for the `libui` use case.

If downloaded from the releases page, the ideal would be for the library to be as small as possible (in other words, no examples, stripped binary, et cetera), in order to facilitate distribution.
